/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ErtekelesRouteImport } from './routes/ertekeles'
import { Route as IndexRouteImport } from './routes/index'

const ErtekelesRoute = ErtekelesRouteImport.update({
  id: '/ertekeles',
  path: '/ertekeles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ertekeles': typeof ErtekelesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ertekeles': typeof ErtekelesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ertekeles': typeof ErtekelesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ertekeles'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ertekeles'
  id: '__root__' | '/' | '/ertekeles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErtekelesRoute: typeof ErtekelesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ertekeles': {
      id: '/ertekeles'
      path: '/ertekeles'
      fullPath: '/ertekeles'
      preLoaderRoute: typeof ErtekelesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErtekelesRoute: ErtekelesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
