/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Pets2IndexRouteImport } from './routes/pets2/index'
import { Route as Pets1IndexRouteImport } from './routes/pets1/index'
import { Route as PetsIndexRouteImport } from './routes/pets/index'
import { Route as PetsIndexcopyRouteImport } from './routes/pets/index copy'
import { Route as PetsCreateRouteImport } from './routes/pets/create'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as Pets2IdEditRouteImport } from './routes/pets2/$id/edit'
import { Route as Pets1IdEditRouteImport } from './routes/pets1/$id/edit'
import { Route as Pets1IdCreateRouteImport } from './routes/pets1/$id/create'
import { Route as PetsIdEditRouteImport } from './routes/pets/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Pets2IndexRoute = Pets2IndexRouteImport.update({
  id: '/pets2/',
  path: '/pets2/',
  getParentRoute: () => rootRouteImport,
} as any)
const Pets1IndexRoute = Pets1IndexRouteImport.update({
  id: '/pets1/',
  path: '/pets1/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsIndexRoute = PetsIndexRouteImport.update({
  id: '/pets/',
  path: '/pets/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsIndexcopyRoute = PetsIndexcopyRouteImport.update({
  id: '/pets/index copy',
  path: '/pets/index copy',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsCreateRoute = PetsCreateRouteImport.update({
  id: '/pets/create',
  path: '/pets/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const Pets2IdEditRoute = Pets2IdEditRouteImport.update({
  id: '/pets2/$id/edit',
  path: '/pets2/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const Pets1IdEditRoute = Pets1IdEditRouteImport.update({
  id: '/pets1/$id/edit',
  path: '/pets1/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const Pets1IdCreateRoute = Pets1IdCreateRouteImport.update({
  id: '/pets1/$id/create',
  path: '/pets1/$id/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsIdEditRoute = PetsIdEditRouteImport.update({
  id: '/pets/$id/edit',
  path: '/pets/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/pets/create': typeof PetsCreateRoute
  '/pets/index copy': typeof PetsIndexcopyRoute
  '/pets': typeof PetsIndexRoute
  '/pets1': typeof Pets1IndexRoute
  '/pets2': typeof Pets2IndexRoute
  '/pets/$id/edit': typeof PetsIdEditRoute
  '/pets1/$id/create': typeof Pets1IdCreateRoute
  '/pets1/$id/edit': typeof Pets1IdEditRoute
  '/pets2/$id/edit': typeof Pets2IdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/pets/create': typeof PetsCreateRoute
  '/pets/index copy': typeof PetsIndexcopyRoute
  '/pets': typeof PetsIndexRoute
  '/pets1': typeof Pets1IndexRoute
  '/pets2': typeof Pets2IndexRoute
  '/pets/$id/edit': typeof PetsIdEditRoute
  '/pets1/$id/create': typeof Pets1IdCreateRoute
  '/pets1/$id/edit': typeof Pets1IdEditRoute
  '/pets2/$id/edit': typeof Pets2IdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/pets/create': typeof PetsCreateRoute
  '/pets/index copy': typeof PetsIndexcopyRoute
  '/pets/': typeof PetsIndexRoute
  '/pets1/': typeof Pets1IndexRoute
  '/pets2/': typeof Pets2IndexRoute
  '/pets/$id/edit': typeof PetsIdEditRoute
  '/pets1/$id/create': typeof Pets1IdCreateRoute
  '/pets1/$id/edit': typeof Pets1IdEditRoute
  '/pets2/$id/edit': typeof Pets2IdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/pets/create'
    | '/pets/index copy'
    | '/pets'
    | '/pets1'
    | '/pets2'
    | '/pets/$id/edit'
    | '/pets1/$id/create'
    | '/pets1/$id/edit'
    | '/pets2/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/pets/create'
    | '/pets/index copy'
    | '/pets'
    | '/pets1'
    | '/pets2'
    | '/pets/$id/edit'
    | '/pets1/$id/create'
    | '/pets1/$id/edit'
    | '/pets2/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/pets/create'
    | '/pets/index copy'
    | '/pets/'
    | '/pets1/'
    | '/pets2/'
    | '/pets/$id/edit'
    | '/pets1/$id/create'
    | '/pets1/$id/edit'
    | '/pets2/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  PetsCreateRoute: typeof PetsCreateRoute
  PetsIndexcopyRoute: typeof PetsIndexcopyRoute
  PetsIndexRoute: typeof PetsIndexRoute
  Pets1IndexRoute: typeof Pets1IndexRoute
  Pets2IndexRoute: typeof Pets2IndexRoute
  PetsIdEditRoute: typeof PetsIdEditRoute
  Pets1IdCreateRoute: typeof Pets1IdCreateRoute
  Pets1IdEditRoute: typeof Pets1IdEditRoute
  Pets2IdEditRoute: typeof Pets2IdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets2/': {
      id: '/pets2/'
      path: '/pets2'
      fullPath: '/pets2'
      preLoaderRoute: typeof Pets2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets1/': {
      id: '/pets1/'
      path: '/pets1'
      fullPath: '/pets1'
      preLoaderRoute: typeof Pets1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/': {
      id: '/pets/'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof PetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/index copy': {
      id: '/pets/index copy'
      path: '/pets/index copy'
      fullPath: '/pets/index copy'
      preLoaderRoute: typeof PetsIndexcopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/create': {
      id: '/pets/create'
      path: '/pets/create'
      fullPath: '/pets/create'
      preLoaderRoute: typeof PetsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets2/$id/edit': {
      id: '/pets2/$id/edit'
      path: '/pets2/$id/edit'
      fullPath: '/pets2/$id/edit'
      preLoaderRoute: typeof Pets2IdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets1/$id/edit': {
      id: '/pets1/$id/edit'
      path: '/pets1/$id/edit'
      fullPath: '/pets1/$id/edit'
      preLoaderRoute: typeof Pets1IdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets1/$id/create': {
      id: '/pets1/$id/create'
      path: '/pets1/$id/create'
      fullPath: '/pets1/$id/create'
      preLoaderRoute: typeof Pets1IdCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/$id/edit': {
      id: '/pets/$id/edit'
      path: '/pets/$id/edit'
      fullPath: '/pets/$id/edit'
      preLoaderRoute: typeof PetsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  PetsCreateRoute: PetsCreateRoute,
  PetsIndexcopyRoute: PetsIndexcopyRoute,
  PetsIndexRoute: PetsIndexRoute,
  Pets1IndexRoute: Pets1IndexRoute,
  Pets2IndexRoute: Pets2IndexRoute,
  PetsIdEditRoute: PetsIdEditRoute,
  Pets1IdCreateRoute: Pets1IdCreateRoute,
  Pets1IdEditRoute: Pets1IdEditRoute,
  Pets2IdEditRoute: Pets2IdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
